; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_thunder
	.word @sfx_ntsc_select

@sfx_ntsc_thunder:
	.byte $8a,$0d,$89,$3f,$0b,$89,$3e,$03,$89,$3d,$02,$89,$3c,$02,$89,$3b
	.byte $02,$89,$3a,$02,$89,$39,$02,$89,$38,$01,$89,$37,$02,$89,$36,$02
	.byte $89,$35,$02,$89,$34,$01,$89,$33,$02,$89,$32,$02,$89,$31,$04,$00
@sfx_ntsc_select:
	.byte $82,$00,$81,$6a,$80,$3f,$85,$00,$84,$9f,$83,$3f,$87,$6a,$88,$00
	.byte $86,$8f,$8a,$00,$89,$3f,$01,$80,$3d,$83,$3d,$86,$8d,$89,$3d,$01
	.byte $80,$3b,$83,$3b,$86,$8b,$89,$3b,$01,$80,$39,$83,$39,$86,$89,$89
	.byte $39,$02,$81,$4f,$80,$3f,$83,$30,$89,$f0,$01,$80,$3d,$01,$80,$3b
	.byte $01,$80,$39,$02,$81,$34,$80,$3f,$84,$7e,$83,$3f,$86,$80,$01,$80
	.byte $3d,$83,$3d,$01,$80,$3b,$83,$3b,$01,$80,$39,$83,$39,$02,$80,$30
	.byte $00

.export sounds
